server:
  port: 8083
  servlet:
    context-path: /post

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: "mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:root}@${MONGO_HOST:mongodb}:27017/post-service?authSource=admin"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: post-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO
    com.khiem: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

app:
  services:
    profile:
      url: "http://${PROFILE_SERVICE_HOST:profile-service}:8081/profile"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
