server:
  port: 8087

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/bookvault?authSource=admin

  error:
    include-message: always
    include-binding-errors: always
