server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  neo4j:
    uri: "bolt://${NEO4J_HOST:neo4j}:7687"
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:12345678}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: profile-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    properties:
      auto.create.topics.enable: true

logging:
  level:
    root: INFO
    com.khiem: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

app:
  services:
    file: "http://${FILE_SERVICE_HOST:file-service}:8084/file"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
